name: ubuntu_flavor_installer

packages:
  - .
  - vendor/ubuntu-desktop-provision/packages/**

ignore:
  - synthetic_package

scripts:
  analyze: >
    melos exec -c 1 --scope="ubuntu_flavor_installer" -- \
      flutter analyze lib

  format: >
    melos exec -c 1 --fail-fast --scope="ubuntu_flavor_installer" -- \
      "find $MELOS_PACKAGE_PATH -name '*.dart' \
          ! -name '*.g.dart' \
          ! -name '*.freezed.dart' \
          ! -path '*/l10n/*' \
          ! -path '*/.*/*' \
          | xargs dart format --set-exit-if-changed"

  generate: >
    melos exec -c 1 --fail-fast --depends-on="build_runner" --scope="ubuntu_flavor_installer" -- \
      dart run build_runner build --delete-conflicting-outputs

  gen-l10n: >
    melos exec -c 1 --fail-fast --scope="ubuntu_flavor_installer" -- \
     flutter gen-l10n

  integration_test: >
    melos exec -c 1 --fail-fast --dir-exists=integration_test --scope="ubuntu_flavor_installer" -- \
      flutter test integration_test

  # runs "flutter pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- flutter pub "$@"

  test: >
    melos exec -c 1 --fail-fast --dir-exists=test --scope="ubuntu_flavor_installer" -- \
      flutter test
